### ISSUE TITLE
[Question]: How to deal with negative demand segments in Demand Data

### ISSUE THREAD

**Issue by MADNANTARRAR** [GenXProject/GenX.jl#729]
### Question

Hi,

I have negative demand segments in my demand data. When I proceed with these negative values, GenX gives me an error indicating that the NSE constraint is violated. Currently, I am considering those negative segments as zero, but this is obviously not the correct representation of the demand data. How can I deal with this issue? Thank you!

I have attached the error picture here:
![image](https://github.com/user-attachments/assets/c0acba8c-4cb3-4405-ba83-c1f89f56af1b)

**Comment by cfe316** [comment]
Hello MADNANTARRAR,

Here are some hints:

- In GenX, demand is defined to be always positive. 
- If you want to model behind-the-meter solar PV which is not controlled, consider the MUST_RUN resource type: https://genxproject.github.io/GenX.jl/stable/Model_Reference/Resources/must_run/
- "Non-served energy" is something entirely different. It is demand that is not met, because the grid cannot supply enough electricity. This is like brownouts, blackouts, and involuntary power shut-offs. It is always an output of the code, and not an input.

A situation where the must-run PV power exceeds demand is tricky. I'm not sure that GenX is currently configured to handle this situation. Mathematically there needs to be an extra demand sink.

One thing you could do with excess power in GenX is use the ELECTROLYZER to produce hydrogen fuels. 

Hope this helps.

**Comment by MADNANTARRAR** [comment]
Thank you for the explanation. I understand the point now

**Comment by MADNANTARRAR** [comment]
Done!
